version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ${APP_NAME}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./backendsapi
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
      RUST_LOG: ${RUST_LOG_LEVEL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  site:
    build:
      context: ./frontends/site
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    container_name: ${APP_NAME}_site
    depends_on:
      api:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${SITE_PORT}
      API_URL: http://api:${API_PORT}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "${SITE_PORT}:${SITE_PORT}"
    restart: unless-stopped

  admin:
    build:
      context: ./frontends/admin
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    container_name: ${APP_NAME}_admin
    depends_on:
      api:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${ADMIN_PORT}
      API_URL: http://api:${API_PORT}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      SESSION_SECRET: ${ADMIN_SESSION_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    restart: unless-stopped

  # nginx:
  #   image: nginx:alpine
  #   container_name: ${APP_NAME}_nginx
  #   depends_on:
  #     - site
  #     - admin
  #     - api
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #     - nginx_logs:/var/log/nginx
  #   ports:
  #     - "${HTTP_PORT}:80"
  #     - "${HTTPS_PORT}:443"
  #   restart: unless-stopped
  #   environment:
  #     - DOMAIN=${DOMAIN}
  #     - API_UPSTREAM=api:${API_PORT}
  #     - SITE_UPSTREAM=site:${SITE_PORT}
  #     - ADMIN_UPSTREAM=admin:${ADMIN_PORT}

  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME}_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  # nginx_logs:
  #   driver: local

networks:
  default:
    name: ${APP_NAME}_network
    driver: bridge
