version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: ${APP_NAME}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal

  api:
    image: debian:bookworm-slim
    container_name: ${APP_NAME}_api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
      RUST_LOG: ${RUST_LOG_LEVEL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal
    # 임시로 간단한 HTTP 서버 실행 (나중에 실제 API로 교체)
    command: >
      sh -c "apt-get update && apt-get install -y curl && 
             echo 'API 서버가 시작되었습니다.' && 
             while true; do sleep 30; done"

  site:
    build:
      context: ./frontends/site
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    container_name: ${APP_NAME}_site
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${SITE_PORT}
      API_URL: http://api:${API_PORT}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "127.0.0.1:${SITE_PORT}:${SITE_PORT}"
    restart: unless-stopped
    networks:
      - internal

  admin:
    build:
      context: ./frontends/admin
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    container_name: ${APP_NAME}_admin
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${ADMIN_PORT}
      API_URL: http://api:${API_PORT}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      SESSION_SECRET: ${ADMIN_SESSION_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "127.0.0.1:${ADMIN_PORT}:${ADMIN_PORT}"
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:6-alpine
    container_name: ${APP_NAME}_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  internal:
    name: ${APP_NAME}_internal
    driver: bridge
