version: '3.8'

services:
  # Rust API (PostgreSQL과 Redis는 서버에서 직접 사용)
  api:
    build:
      context: ./backends/api
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-mincenter}_api
    environment:
      # 서버의 PostgreSQL과 Redis 사용
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      API_PORT: ${API_PORT:-18080}
      RUST_LOG: ${RUST_LOG_LEVEL:-info}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "${API_PORT:-18080}:${API_PORT:-18080}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-18080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Note: Site and Admin are deployed to Cloudflare Pages automatically
  # PostgreSQL and Redis are running directly on the server
