name = "mincenter-site"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "build"

[env.production]
name = "mincenter-site-prod"

[env.staging]
name = "mincenter-site-staging"
