name: Debug SSH Connection

on:
  workflow_dispatch:

jobs:
  debug-ssh:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Secrets
        run: |
          echo "=== GitHub Secrets 확인 ==="
          echo "DEPLOY_HOST 길이: ${#DEPLOY_HOST}"
          echo "DEPLOY_USER 길이: ${#DEPLOY_USER}"
          echo "DEPLOY_SSH_KEY 길이: ${#DEPLOY_SSH_KEY}"
          echo "DEPLOY_PATH 길이: ${#DEPLOY_PATH}"
          
          if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then
            echo "❌ DEPLOY_HOST가 비어있습니다!"
          else
            echo "✅ DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}"
          fi
          
          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
            echo "❌ DEPLOY_USER가 비어있습니다!"
          else
            echo "✅ DEPLOY_USER: ${{ secrets.DEPLOY_USER }}"
          fi
          
          if [ -z "${{ secrets.DEPLOY_SSH_KEY }}" ]; then
            echo "❌ DEPLOY_SSH_KEY가 비어있습니다!"
          else
            echo "✅ DEPLOY_SSH_KEY가 설정되어 있습니다."
            echo "키 시작: $(echo '${{ secrets.DEPLOY_SSH_KEY }}' | head -1)"
            echo "키 끝: $(echo '${{ secrets.DEPLOY_SSH_KEY }}' | tail -1)"
          fi
          
          if [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
            echo "❌ DEPLOY_PATH가 비어있습니다!"
          else
            echo "✅ DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}"
          fi
          echo "=========================="
      
      - name: Setup SSH Key
        run: |
          echo "=== SSH 키 설정 ==="
          mkdir -p ~/.ssh
          echo '${{ secrets.DEPLOY_SSH_KEY }}' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "SSH 키 파일 생성됨:"
          ls -la ~/.ssh/deploy_key
          echo "SSH 키 시작:"
          head -1 ~/.ssh/deploy_key
          echo "SSH 키 끝:"
          tail -1 ~/.ssh/deploy_key
          echo "=================="
      
      - name: Test SSH Connection
        run: |
          echo "=== SSH 연결 테스트 ==="
          
          # SSH 연결 테스트
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -v \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
              "echo 'SSH 연결 성공!' && hostname && whoami && pwd"
          
          echo "========================"
      
      - name: Test with ssh-action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "=== ssh-action을 통한 연결 테스트 ==="
            echo "호스트: $(hostname)"
            echo "IP 주소: $(hostname -I | awk '{print $1}')"
            echo "사용자: $(whoami)"
            echo "현재 경로: $(pwd)"
            echo "현재 시간: $(date)"
            echo "================================" 