name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Configure SSH for CentOS 7
      run: |
        mkdir -p ~/.ssh
        cat >> ~/.ssh/config << EOF
        Host ${{ secrets.SERVER_HOST }}
          HostName ${{ secrets.SERVER_HOST }}
          User ${{ secrets.SERVER_USER }}
          Port 22000
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        EOF
        
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H -p 22000 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        ssh ${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          ./scripts/deploy.sh
        EOF
        
    - name: Health check
      run: |
        sleep 60
        curl -f ${{ secrets.SITE_URL }}/health || echo "사이트 헬스체크 실패"
        curl -f ${{ secrets.ADMIN_URL }}/health || echo "관리자 페이지 헬스체크 실패"
        curl -f ${{ secrets.API_URL }}/health || echo "API 헬스체크 실패" 