name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

# GitHub Container Registry 권한 설정
permissions:
  contents: read
  packages: write
  actions: read

jobs:
  # 변경 감지
  detect-changes:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    outputs:
      site-changed: ${{ steps.changes.outputs.site }}
      admin-changed: ${{ steps.changes.outputs.admin }}
      api-changed: ${{ steps.changes.outputs.api }}
      env-changed: ${{ steps.changes.outputs.env }}
      db-changed: ${{ steps.changes.outputs.db }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5  # 최근 5개 커밋과 비교하기 위해

      - name: Detect changes
        id: changes
        run: |
          # 이전 커밋과 비교하여 변경된 파일 감지
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # PR이 머지된 경우
            git fetch origin ${{ github.base_ref }}
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          else
            # 직접 push된 경우 (최근 3개 커밋 범위로 확장)
            CHANGED_FILES=$(git diff --name-only HEAD~3...HEAD 2>/dev/null || git diff --name-only HEAD~1...HEAD)
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # 각 컴포넌트별 변경 감지
          if echo "$CHANGED_FILES" | grep -q "^frontends/site/"; then
            echo "site=true" >> $GITHUB_OUTPUT
            echo "Site changes detected:"
            echo "$CHANGED_FILES" | grep "^frontends/site/"
          else
            echo "site=false" >> $GITHUB_OUTPUT
            echo "No site changes detected"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^frontends/admin/"; then
            echo "admin=true" >> $GITHUB_OUTPUT
            echo "Admin changes detected:"
            echo "$CHANGED_FILES" | grep "^frontends/admin/"
          else
            echo "admin=false" >> $GITHUB_OUTPUT
            echo "No admin changes detected"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^backends/api/"; then
            echo "api=true" >> $GITHUB_OUTPUT
          else
            echo "api=false" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^\.env"; then
            echo "env=true" >> $GITHUB_OUTPUT
          else
            echo "env=false" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^database/"; then
            echo "db=true" >> $GITHUB_OUTPUT
          else
            echo "db=false" >> $GITHUB_OUTPUT
          fi

  # 사이트 배포 (Docker 이미지 방식)
  deploy-site:
    needs: detect-changes
    if: needs.detect-changes.outputs.site-changed == 'true'
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create environment file
        run: |
          cd frontends/site
          cat > .env.production << EOF
          VITE_API_URL=https://api.mincenter.kr
          PUBLIC_API_URL=https://api.mincenter.kr
          API_BASE_URL=https://api.mincenter.kr
          NODE_ENV=production
          PUBLIC_DOMAIN=mincenter.kr
          EOF
          echo "=== 환경변수 파일 생성 완료 ==="
          cat .env.production
      
      - name: Build and push site Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontends/site
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mincenter-site:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mincenter-site:latest
          build-args: |
            VITE_API_URL=https://api.mincenter.kr
            PUBLIC_API_URL=https://api.mincenter.kr
            API_BASE_URL=https://api.mincenter.kr
            NODE_ENV=production
            PUBLIC_DOMAIN=mincenter.kr
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "=== 서버 정보 (FIXED VERSION) ==="
            echo "호스트: $(hostname)"
            echo "IP 주소: $(hostname -I | awk '{print $1}')"
            echo "배포 경로: ${{ secrets.DEPLOY_PATH }}"
            echo "현재 시간: $(date)"
            echo "=================="
            cd ${{ secrets.DEPLOY_PATH }}
            echo "=== 파일 확인 ==="
            ls -la docker-compose*
            echo "=================="
            echo "=== 기존 컨테이너 상태 ==="
            docker compose ps
            echo "========================="
            echo "=== 새 이미지 pull ==="
            docker pull ghcr.io/${{ github.repository_owner }}/mincenter-site:${{ github.sha }}
            echo "=== 이미지 pull 완료 ==="
            echo "=== nginx proxy manager 네트워크 확인 ==="
            NPM_NETWORK=$(docker network ls | grep -i nginx | awk '{print $2}' | head -n1)
            if [ -z "$NPM_NETWORK" ]; then
                NPM_NETWORK="nginxproxymanager_default"
                echo "기본 네트워크 이름 사용: $NPM_NETWORK"
            else
                echo "발견된 nginx 네트워크: $NPM_NETWORK"
            fi
            echo
            echo "=== Docker Compose 파일 업데이트 (수정됨) ==="
            cat > docker-compose.yml << 'EOF'
            version: '3.8'
            
            networks:
              default:
                external: true
                name: proxy
            
            services:
              postgres:
                image: postgres:13-alpine
                container_name: mincenter-postgres
                restart: unless-stopped
                environment:
                  POSTGRES_DB: mincenter
                  POSTGRES_USER: mincenter
                  POSTGRES_PASSWORD: "!@swjp0209^^"
                volumes:
                  - postgres_data:/var/lib/postgresql/data
                  - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
                  - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
                ports:
                  - "15432:5432"
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U mincenter"]
                  interval: 10s
                  timeout: 5s
                  retries: 5
            
              redis:
                image: redis:7-alpine
                container_name: mincenter-redis
                restart: unless-stopped
                command: redis-server --requirepass tnekwoddl
                volumes:
                  - redis_data:/data
                ports:
                  - "16379:6379"
                healthcheck:
                  test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
                  interval: 10s
                  timeout: 5s
                  retries: 5
            
              site:
                image: ghcr.io/${{ github.repository_owner }}/mincenter-site:${{ github.sha }}
                container_name: mincenter-site
                restart: unless-stopped
                depends_on:
                  postgres:
                    condition: service_healthy
                  redis:
                    condition: service_healthy
                ports:
                  - "13000:3000"
                environment:
                  - NODE_ENV=production
                  - PUBLIC_API_URL=https://api.mincenter.kr
                  - API_BASE_URL=https://api.mincenter.kr
                  - PUBLIC_DOMAIN=mincenter.kr
                  - PUBLIC_NODE_ENV=production
                healthcheck:
                  test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
            
              admin:
                image: ghcr.io/${{ github.repository_owner }}/mincenter-admin:${{ github.sha }}
                container_name: mincenter-admin
                restart: unless-stopped
                depends_on:
                  postgres:
                    condition: service_healthy
                  redis:
                    condition: service_healthy
                ports:
                  - "13001:3000"
                environment:
                  - NODE_ENV=production
                  - PUBLIC_API_URL=http://api.mincenter.kr
                  - PUBLIC_DOMAIN=localhost
                  - PUBLIC_NODE_ENV=production
                healthcheck:
                  test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
            
            volumes:
              postgres_data:
              redis_data:
            EOF
            echo "=== Docker Compose 파일 업데이트 완료 ==="
            echo "=== 기존 컨테이너 완전 제거 ==="
            docker compose down site
            docker compose rm -f site
            echo "=== 기존 컨테이너 제거 완료 ==="
            echo "=== 새 컨테이너 생성 ==="
            docker compose up -d site
            echo "=== 새 컨테이너 생성 완료 ==="
            sleep 5
            echo "=== 배포 후 컨테이너 상태 ==="
            docker compose ps
            echo "============================="
            echo "=== 환경변수 확인 ==="
            docker compose exec -T site env | grep -E "(API_BASE_URL|NODE_ENV|PUBLIC_API_URL)" || echo "환경변수 확인 실패"
            echo "============================="
            echo "=== 컨테이너 로그 확인 ==="
            docker compose logs --tail=20 site || echo "로그 확인 실패"
            echo "============================="
            echo "=== Docker Compose 파일 내용 확인 ==="
            grep -A 10 "site:" docker-compose.yml
            echo "===================================="

  # 관리자 배포 (Docker 이미지 방식)
  deploy-admin:
    needs: detect-changes
    if: needs.detect-changes.outputs.admin-changed == 'true'
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create environment file
        run: |
          cd frontends/admin
          cat > .env.production << EOF
          VITE_API_URL=https://api.mincenter.kr
          PUBLIC_API_URL=https://api.mincenter.kr
          API_BASE_URL=https://api.mincenter.kr
          NODE_ENV=production
          PUBLIC_DOMAIN=mincenter.kr
          EOF
          echo "=== Admin 환경변수 파일 생성 완료 ==="
          cat .env.production
      
      - name: Build and push admin Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontends/admin
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mincenter-admin:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mincenter-admin:latest
          build-args: |
            VITE_API_URL=https://api.mincenter.kr
            PUBLIC_API_URL=https://api.mincenter.kr
            API_BASE_URL=https://api.mincenter.kr
            NODE_ENV=production
            PUBLIC_DOMAIN=mincenter.kr
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy admin to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "=== Admin 서버 정보 (FIXED VERSION) ==="
            echo "호스트: $(hostname)"
            echo "IP 주소: $(hostname -I | awk '{print $1}')"
            echo "배포 경로: ${{ secrets.DEPLOY_PATH }}"
            echo "현재 시간: $(date)"
            echo "=================="
            cd ${{ secrets.DEPLOY_PATH }}
            echo "=== Admin 새 이미지 pull ==="
            docker pull ghcr.io/${{ github.repository_owner }}/mincenter-admin:${{ github.sha }}
            echo "=== Admin 이미지 pull 완료 ==="
            echo "=== Admin 컨테이너 업데이트 ==="
            
            # 현재 docker-compose.yml에서 admin 서비스 이미지 태그 업데이트
            sed -i "s|ghcr.io/${{ github.repository_owner }}/mincenter-admin:.*|ghcr.io/${{ github.repository_owner }}/mincenter-admin:${{ github.sha }}|g" docker-compose.yml
            
            echo "=== Admin 컨테이너 재시작 ==="
            docker compose down admin
            docker compose rm -f admin
            docker compose up -d admin
            echo "=== Admin 컨테이너 재시작 완료 ==="
            sleep 5
            echo "=== Admin 배포 후 컨테이너 상태 ==="
            docker compose ps admin
            echo "=== Admin 컨테이너 로그 확인 ==="
            docker compose logs --tail=20 admin || echo "Admin 로그 확인 실패"
            echo "===================================="