name: Secure SSH Connection Test

on:
  workflow_dispatch:

jobs:
  secure-ssh:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH Key
        run: |
          echo "=== SSH 키 설정 ==="
          mkdir -p ~/.ssh
          echo '${{ secrets.DEPLOY_SSH_KEY }}' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # SSH 키 검증
          ssh-keygen -l -f ~/.ssh/deploy_key
          echo "SSH 키 설정 완료"
      
      - name: Test SSH Connection
        run: |
          echo "=== SSH 연결 테스트 ==="
          
          # SSH 연결 테스트 (서버 정보 강제 출력)
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o ConnectTimeout=30 \
              -o ServerAliveInterval=60 \
              -o ServerAliveCountMax=3 \
              -v \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
              'echo "=== 서버 정보 ==="; \
               echo "호스트: $(hostname)"; \
               echo "IP 주소: $(hostname -I | awk "{print \$1}")"; \
               echo "사용자: $(whoami)"; \
               echo "경로: $(pwd)"; \
               echo "시간: $(date)"; \
               echo "=================="; \
               echo "=== 추가 정보 ==="; \
               echo "환경변수: \$SSH_CONNECTION"; \
               echo "프로세스: \$(ps -p \$\$)"; \
               echo "================="'
      
      - name: Test with webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      
      - name: SSH with webfactory
        run: |
          echo "=== webfactory/ssh-agent 테스트 ==="
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
              'echo "호스트: $(hostname)"; echo "사용자: $(whoami)"' 