name: Test Site Direct Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Site Container Direct Access
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            
            echo "=== Site 컨테이너 상태 확인 ==="
            docker compose ps site
            echo
            
            echo "=== Site 컨테이너 로그 (최근 20줄) ==="
            docker compose logs --tail=20 site
            echo
            
            echo "=== Site 컨테이너 내부 접속 테스트 ==="
            docker compose exec -T site curl -f http://localhost:3000 || echo "Site 컨테이너 내부 접속 실패"
            echo
            
            echo "=== 호스트에서 Site 컨테이너 접속 테스트 ==="
            curl -I http://localhost:13000 || echo "호스트에서 Site 접속 실패"
            echo
            
            echo "=== 포트 13000 확인 ==="
            netstat -tlnp | grep 13000 || echo "포트 13000이 열려있지 않음"
            echo
            
            echo "=== Docker 네트워크 확인 ==="
            docker network inspect mincenter_default | grep -A 5 mincenter-site || echo "네트워크에서 site 컨테이너 찾을 수 없음"
            echo
            
            echo "=== nginx proxy manager 관련 프로세스 확인 ==="
            docker ps | grep -i nginx || echo "nginx 관련 컨테이너 없음"
            echo
            
            echo "=== 방화벽 설정 확인 ==="
            iptables -L | grep -E "(13000|80|443)" || echo "방화벽 규칙 없음"