name: Test and Build

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  # 프론트엔드 테스트
  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [site, admin]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontends/${{ matrix.project }}/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontends/${{ matrix.project }}
          npm ci
      
      - name: Run tests
        run: |
          cd frontends/${{ matrix.project }}
          npm test
      
      - name: Build
        run: |
          cd frontends/${{ matrix.project }}
          npm run build

  # 백엔드 테스트
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backends/api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run tests
        run: |
          cd backends/api
          cargo test
      
      - name: Build
        run: |
          cd backends/api
          cargo build --release

  # 보안 검사
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif' 